project_name: cbt

builds:
  - binary: cbt
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tar
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md

release:
  github:
    owner: LoliGothick
    name: cbt
