version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/LoliGothick/cbt

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - run: 
      - run: mkdir -p $TEST_RESULTS
      - run: make preinstall
      - run: make lint
      - run: make build
      - run: 
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test ./... | tee ${TEST_RESULTS}/go-test.out
      - run: goverage -coverprofile=${TEST_RESULTS}/cover.out -covermode=count ./internal/core ./internal/wandbox ./internal/wandbox/expand
      - run: go tool cover -html=${TEST_RESULTS}/cover.out -o ${TEST_RESULTS}/cover.html
      - run: make package
      - store_artifacts:
          path: dist
          destination: binary
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

  release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/